Teachers section
OksanaDonchuk/Project_group_8 pull request #2
Opened 2023-08-29 12:04 UTC by OlgaBieliaieva

2023-08-29 16:41 UTC, OksanaDonchuk requested changes

2023-08-29 16:41 UTC, OksanaDonchuk commented on src/partials/our_teachers.html
> +              srcset="../img/teacher_1@2x.jpg 2x"
В зв’язку зі зміною зображень, необхідно змінити шляхи до зображень, а також зкруглити їх відображення

2023-08-30 05:59 UTC, OlgaBieliaieva commented on src/partials/our_teachers.html
> +              srcset="../img/teacher_1@2x.jpg 2x"
Доброго ранку, все пофіксила, прошу розглянути

2023-08-30 16:37 UTC, OksanaDonchuk approved these changes

2023-08-30 16:37 UTC, merged