Feature hero
OksanaDonchuk/Project_group_8 pull request #3
Opened 2023-08-29 15:44 UTC by AnnaTsepilova

2023-08-29 18:46 UTC, OksanaDonchuk requested changes
Анна, прошу повернути структуру папки img до первинного вигляду (окрім спрайту іконок).
Лапки в url не обов’язкові, але це павило гарного тону та підвищення читабельності коду.
Селектори або теги (id) в медіазапитах потрібні обов’язково, тому що браузер не знає, до чого застосувати це правило.

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  border-radius: 16px;
Повторення рядку 24

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  @media screen and (min-width: 524px) and (max-width: 824px) {
Чому саме такі параметри? в нас точки перелому: mobile: 
   - верстка гумова від 320px, стає адаптивною з 375px;
   - tablet: з 768px;
   - desktop: з 1280px

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  max-width: 425px;
мені здається краще по точці перелому 375px орієнтуватися

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    url(../img/hero/hero-bg-mobile@1x.jpg);
пропущено лапки

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +      url(../img/hero/hero-bg-tablet@1x.jpg);
пропущено лапки

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +        url(../img/hero/hero-bg-tablet@2x.jpg);
пропущено лапки

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    @media (min-device-pixel-ratio: 2),
наскільки я пам’ятаю, такі правила пишуться через and та вказання точки перелому пристрою

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  font-weight: var(--font-weight-bold);
Для заголовка це значення за замовчуванням, в принципі не помилка, але можуть дати зауваження

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  padding: 14px 28px;
по макету padding: 14px 78px

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    padding: 16px 32px;
padding: 16px 64px;

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +  @media screen and (min-width: 768px) {
відсутній селектор, для якого стилі в цьому медіазапиті, доречі такий медіазапит вже є

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    background-image: linear-gradient(
для якого селектора/тегу це правило?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    margin-left: 32px;
відсутній селектор/тег

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    margin-left: 64px;
відсутній селектор/тег

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    max-width: 704px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +      background-image: linear-gradient(
селектор/тег

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    max-width: 1152px;
селектор/тег

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +      background-image: linear-gradient(
селектор/тег

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    gap: 32px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    padding-left: 64px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    max-width: 488px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    max-width: 564px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    width: 306px;
селектор/тег?

2023-08-29 18:46 UTC, OksanaDonchuk commented on src/css/hero.css
> +    right: 32px;
селектор/тег?

2023-08-29 19:43 UTC, AnnaTsepilova commented on src/css/hero.css
> +    margin-left: 32px;
Який саме?

2023-08-29 19:44 UTC, AnnaTsepilova commented on src/css/hero.css
> +    background-image: linear-gradient(
для .hero__bg
Всі медіа знаходяться в середині свої класів

2023-08-29 19:47 UTC, AnnaTsepilova commented on src/css/hero.css
> +    url(../img/hero/hero-bg-mobile@1x.jpg);
+

2023-08-29 19:47 UTC, AnnaTsepilova commented on src/css/hero.css
> +    url(../img/hero/hero-bg-mobile@1x.jpg);
"+"

2023-08-29 19:48 UTC, AnnaTsepilova commented on src/css/hero.css
> +    margin-left: 32px;
Всі медіа знаходяться в середині свої класів

2023-08-29 19:48 UTC, AnnaTsepilova commented on src/css/hero.css
> +    margin-left: 64px;
Всі медіа знаходяться в середині своїх класів

2023-08-29 19:49 UTC, AnnaTsepilova commented on src/css/hero.css
> +  border-radius: 16px;
"+"

2023-08-29 19:49 UTC, AnnaTsepilova commented on src/css/hero.css
> +    max-width: 704px;
Всі медіа знаходяться в середині своїх класів

2023-08-29 19:50 UTC, AnnaTsepilova commented on src/css/hero.css
> +      url(../img/hero/hero-bg-tablet@1x.jpg);
"+"

2023-08-29 19:51 UTC, AnnaTsepilova commented on src/css/hero.css
> +        url(../img/hero/hero-bg-tablet@2x.jpg);
"+"

2023-08-29 19:54 UTC, AnnaTsepilova commented on src/css/hero.css
> +  padding: 14px 28px;
А якщо тексту у кнопки буде забагато, вона буде виглядати як ковбаса. Падінг 78рх на макеті, бо тексту там мало. 
Як казали на дизайні "зазвичай значення горизонтальних падінгів в 2 рази більші, ніж вертикальних"

2023-08-29 19:55 UTC, AnnaTsepilova commented on src/css/hero.css
> +    padding: 16px 32px;
Якщо тексту у кнопки буде забагато, вона буде виглядати як ковбаса. Падінг 64рх на макеті, бо тексту там мало.
Як казали на дизайні "зазвичай значення горизонтальних падінгів в 2 рази більші, ніж вертикальних"

2023-08-29 20:07 UTC, AnnaTsepilova commented on src/css/hero.css
> +  font-weight: var(--font-weight-bold);
"+"

2023-08-29 20:07 UTC, AnnaTsepilova commented on src/css/hero.css
> +    @media (min-device-pixel-ratio: 2),
в конспекті без "and"

2023-08-29 20:22 UTC, AnnaTsepilova commented on src/css/hero.css
> +    margin-left: 32px;
цей підхід до написання медіа-запитів має корені у методології sass
Як на мене, він набагато зручніший. Тут не треба шукати по всій простині коду де ти міняв якесь значення.
Все компактно лежить в своєму класі.

2023-08-29 20:28 UTC, OksanaDonchuk requested changes

2023-08-29 20:28 UTC, OksanaDonchuk commented on src/css/hero.css
> +    margin-left: 32px;
методологія sass не працює в сучасній методології чистого CSS, а ми зараз робимо саме на ньому

2023-08-29 20:28 UTC, OksanaDonchuk commented on src/css/hero.css
> +    @media (min-device-pixel-ratio: 2),
В конспекті так, але на уроках нам на це вказував викладач

2023-08-29 20:28 UTC, OksanaDonchuk commented on src/css/hero.css
> +  padding: 14px 28px;
в нас в ТЗ прописано, що все повинно відповідати макету

2023-08-29 21:26 UTC, AnnaTsepilova commented on src/css/hero.css
> +  @media screen and (min-width: 524px) and (max-width: 824px) {
Я переробила під жорсткі правила.
Але ще є практика, коли додають інші брекпоінти, якщо (наприклад, як у героя) специфічна картинка.

2023-08-30 17:44 UTC, OksanaDonchuk approved these changes

2023-08-30 17:45 UTC, merged