about us section
OksanaDonchuk/Project_group_8 pull request #4
Opened 2023-08-29 16:49 UTC by KovalchukAIWE

2023-08-29 19:31 UTC, OksanaDonchuk requested changes
Не всі значенн стилів знайшла в макеті, тому зауваження даю, але може десь не додивилась?

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  gap: 32px;
це ж мобільна версія? де там 32px?

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  border-radius: 30px;
Йдемо від мобільної, а значить в базових стилях бордео-радіус 16

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  font-weight: 700;
тут краще використати змінну для font-weight

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  letter-spacing: -0.36px;
letter-spacing: -0.02;

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  border-radius: 30px;
в мобільній радіус 16

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  padding: 70px 0;
не зрозуміла, де в мобільному padding: 70

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +  .about-us--card {
тут треба зробити через calc

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +    padding: 16px 0;
не знайшла в padding: 16, де саме?

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +    .about-us--card {
Знову функція calc додає гнучкості

2023-08-29 19:31 UTC, OksanaDonchuk commented on src/css/about_us.css
> +      padding: 51px 0;
це padding від чого до чого?

2023-08-30 16:09 UTC, KovalchukAIWE commented on src/css/about_us.css
> +  .about-us--card {
Не можу реалізувати через calc - ломається розмітка. Гнучкості це не надасть, тому що в нас адаптивна верстка. "Резиновими" карточки будуть на мобільній версії при width:100%

2023-08-30 18:15 UTC, OksanaDonchuk approved these changes

2023-08-30 18:15 UTC, merged