Header
OksanaDonchuk/Project_group_8 pull request #8
Opened 2023-08-30 20:36 UTC by SerhiiOsmolovskyi

Added header and mobile menu, first attempt. I would like to consider some moments when you have time.

2023-08-30 20:40 UTC, SerhiiOsmolovskyi commented
Next time

2023-08-30 21:01 UTC, OksanaDonchuk requested changes
Подивись в мобільній та планшетній версій меню навігації по макету вище, ніж в тебе, плюс там по файлу html зауваження: перший зайвий рядок та треба для навігації id якори поставити

2023-08-30 21:01 UTC, OksanaDonchuk commented on src/partials/header.html
> -<header></header>
зайвий рядок

2023-08-30 21:01 UTC, OksanaDonchuk commented on src/partials/header.html
> +          <a href="" class="page-header-nav-menu-link link active">About us</a>
додай якоря для навігації

2023-08-31 17:34 UTC, sem-aa commented on src/css/header.css
> +
гадаю краще спозиціонувати через флекс по центру. Падинг дуже великий і якщо ми повертаемо телефон не бачимо меню

2023-08-31 17:38 UTC, sem-aa commented on src/css/header.css
> +
gap не працює, бо сжат іншим флексом

2023-08-31 18:03 UTC, sem-aa commented on src/css/header.css
> + .page-header-mobile-menu-container {
теж саме, стоїть не по центру, ні як в макеті. І gap не працює.

2023-08-31 18:09 UTC, sem-aa reviewed
краще змінити позиціонування без великих паддингів

2023-08-31 20:47 UTC, OksanaDonchuk approved these changes

2023-08-31 20:47 UTC, merged